### ISSUE TITLE
Possible to trigger multiple modals

### ISSUE THREAD

**Issue by jackbrewer** [bengourley/modal.js#15]
If a modal is triggered by a button click, a modal appears as expected. If you press the enter key again, the original button (which still has focus) is 'clicked' again, causing a second modal to appear. Subsequent 'clicks' = extra stacked modals.

Originally I though we should close existing modals whenever another is triggered, but this would break good functionality where we can trigger as second modal from within another. I think the best thing for now could be to move keyboard focus to each modal, as soon as it is opened. Open for suggestion.

**Comment by bengourley** [comment]
I agree, the model element should receive focus.
